# Generated by Django 5.2.3 on 2025-07-08 03:39

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('pessoas', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='pessoa',
            old_name='cpf',
            new_name='cpf_cnpj',
        ),
    ]
